### ISSUE TITLE
Export failed

### ISSUE THREAD

**Issue by bsms-bsoft** [globocom/GloboDNS#31]
I have installed a fresh copy of GloboDNS and facing blow error in bind9 page when i click or export button

Export failed
Exporting 0 zones, but the database have 6 zones

Errors mentioned in log file:
App 25638 output: Application version is 'DEVELOPMENT'
App 25816 output: chown :named /tmp/d20190919-25816-1s6eiym

backtrace: ["/var/www/html/globodns/lib/globo_dns/exporter.rb:885:in `check_zones_being_exported'", "/var/www/html/globodns/lib/globo_dns/exporter.rb:227:in `export'", "/var/www/html/globodns/lib/globo_dns/exporter.rb:82:in `export_master'", "/var/www/html/globodns/lib/globo_dns/exporter.rb:53:in `export_all'", "/var/www/html/globodns/app/controllers/bind9_controller.rb:109:in `run_export'", "/var/www/html/globodns/app/controllers/bind9_controller.rb:38:in `export'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/abstract_controller/base.rb:198:in `process_action'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal/rendering.rb:10:in `process_action'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/rails-observers-0.1.5/lib/rails/observers/action_controller/caching/sweeper.rb:24:in `around'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:455:in `public_send'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:455:in `block in make_lambda'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:312:in `block in halting'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:497:in `block in around'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/abstract_controller/callbacks.rb:19:in `process_action'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal/rescue.rb:29:in `process_action'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:164:in `block in instrument'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:164:in `instrument'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/abstract_controller/base.rb:137:in `process'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionview-4.2.11.1/lib/action_view/rendering.rb:30:in `process'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal.rb:196:in `dispatch'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal.rb:237:in `block in action'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/journey/router.rb:30:in `each'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/journey/router.rb:30:in `serve'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/routing/route_set.rb:817:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/rack-1.6.11/lib/rack/etag.rb:24:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/rack-1.6.11/lib/rack/conditionalget.rb:38:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/rack-1.6.11/lib/rack/head.rb:13:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/flash.rb:260:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:225:in `context'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:220:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/query_cache.rb:36:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/rack/logger.rb:38:in `call_app'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/rack/logger.rb:20:in `block in call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:26:in `tagged'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:68:in `tagged'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/rack/logger.rb:20:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/rack-1.6.11/lib/rack/methodoverride.rb:22:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/rack-1.6.11/lib/rack/runtime.rb:18:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/static.rb:120:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/rack-1.6.11/lib/rack/sendfile.rb:113:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/engine.rb:518:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/application.rb:165:in `call'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `public_send'", "/var/www/html/globodns/vendor/cache/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `method_missing'", "/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'", "/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'", "/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'", "/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'", "/usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'"]

**Comment by ernestothorp** [comment]
The branch you are use, has a feature that will check the actual zones and exported zones.
If percentual diference is above X%, the export will fail.

> Export failed
> Exporting 0 zones, but the database have 6 zones

function 
`"/var/www/html/globodns/lib/globo_dns/exporter.rb:885:in check_zones_being_exported'"`
