### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by ebasse-prog** [globocom/GloboDNS#33]
Can't start globodns site.
"We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly."

In logs:

Sep 15 10:19:19 localhost globodns[18560]: [Internal Server Error] exception: [ERROR] 'git last commit date' failed: pid 19515 exit 128 (fatal: your current branch 'master' does not have any commits yet\n)\n/root/globodns/lib/globo_dns/util.rb:37:in `exec'\n/root/globodns/lib/globo_dns/util.rb:65:in `block in last_export_timestamp'\n/root/globodns/lib/globo_dns/util.rb:64:in `chdir'\n/root/globodns/lib/globo_dns/util.rb:64:in `last_export_timestamp'\n/root/globodns/app/helpers/application_helper.rb:19:in `last_export_timestamp'\n/root/globodns/app/views/layouts/application.html.erb:27:in `_app_views_layouts_application_html_erb___316019210200909629_37183880'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionview-4.2.11.1/lib/action_view/template.rb:145:in `block in render'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:166:in `instrument'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionview-4.2.11.1/lib/action_view/template.rb:333:in `instrument'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionview-4.2.11.1/lib/action_view/template.rb:143:in `render'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionview-4.2.11.1/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionview-4.2.11.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionview-4.2.11.1/lib/action_view/renderer/template_renderer.rb:14:in `render'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionview-4.2.11.1/lib/action_view/renderer/renderer.rb:46:in `render_template'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionview-4.2.11.1/lib/action_view/renderer/renderer.rb:27:in `render'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionview-4.2.11.1/lib/action_view/rendering.rb:100:in `_render_template'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionview-4.2.11.1/lib/action_view/rendering.rb:83:in `render_to_body'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/abstract_controller/rendering.rb:25:in `render'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/rendering.rb:16:in `render'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'\n/usr/local/rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-4.2.11.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/instrumentation.rb:43:in `render'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/implicit_render.rb:10:in `default_render'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/implicit_render.rb:5:in `send_action'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/abstract_controller/base.rb:198:in `process_action'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/rendering.rb:10:in `process_action'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117:in `call'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505:in `call'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'\n/usr/local/rvm/gems/ruby-2.5.7/gems/rails-observers-0.1.5/lib/rails/observers/action_controller/caching/sweeper.rb:24:in `around'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:455:in `public_send'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:455:in `block in make_lambda'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:312:in `block in halting'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:497:in `block in around'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505:in `call'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:81:in `run_callbacks'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/abstract_controller/callbacks.rb:19:in `process_action'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/rescue.rb:29:in `process_action'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:164:in `block in instrument'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:164:in `instrument'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'\n/usr/local/rvm/gems/ruby-2.5.7/gems/activerecord-4.2.11.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/abstract_controller/base.rb:137:in `process'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionview-4.2.11.1/lib/action_view/rendering.rb:30:in `process'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal.rb:196:in `dispatch'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_controller/metal.rb:237:in `block in action'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_dispatch/journey/router.rb:30:in `each'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_dispatch/journey/router.rb:30:in `serve'\n/usr/local/rvm/gems/ruby-2.5.7/gems/actionpack-4.2.11.1/lib/action_dispatch/routing/route_set.rb:817:in `call'\n/usr/local/rvm/gems/ruby-2.5.7/gem
Sep 15 10:19:19 localhost globodns[18560]: Completed 500 Internal Server Error in 19ms (ActiveRecord: 1.8ms)
Sep 15 10:19:19 localhost globodns[18560]: GloboDns::Util::ExitStatusError ([ERROR] 'git last commit date' failed: pid 19515 exit 128 (fatal: your current branch 'master' does not have any commits yet\n)):\n  lib/globo_dns/util.rb:37:in `exec'\n  lib/globo_dns/util.rb:65:in `block in last_export_timestamp'\n  lib/globo_dns/util.rb:64:in `chdir'\n  lib/globo_dns/util.rb:64:in `last_export_timestamp'\n  app/helpers/application_helper.rb:19:in `last_export_timestamp'\n  app/views/layouts/application.html.erb:27:in `_app_views_layouts_application_html_erb___316019210200909629_37183880'
Sep 15 10:19:20 localhost rsyslogd[1826]: message too long (12436) with configured size 8096, begin of message is: [Internal Server Error] exception: [ERROR] 'git last commit date' failed: pid 19 [v8.37.0-13.el8 try http://www.rsyslog.com/e/2445 ]

**Comment by glafir** [comment]
```
rsyslogd[1826]: message too long
```
The parameter :

$MaxMessageSize 8096

must be set before network declaration (at the top of /etc/rsyslog.conf file) :
```
$ModLoad imtcp
$InputTCPServerRun 1514
```
